// ============================================================
// App -- Tab switching, copy/download, initialization
// Depends on: SynthEngine, AppState, SerialBridge, SynthUI, ConfigGenerator
// ============================================================

(function () {
  "use strict";

  function $(sel) { return document.querySelector(sel); }

  // --- Tab switching -------------------------------------------------------

  function switchTab(tabName) {
    var tabs = document.querySelectorAll(".tab");
    for (var i = 0; i < tabs.length; i++) {
      var active = tabs[i].getAttribute("data-tab") === tabName;
      tabs[i].classList.toggle("active", active);
      tabs[i].setAttribute("aria-selected", active ? "true" : "false");
    }
    var panels = document.querySelectorAll(".tab-panel");
    for (var j = 0; j < panels.length; j++) {
      panels[j].classList.toggle("active", panels[j].id === "tab-" + tabName);
    }
    // Render config panel whenever switching to it (picks up latest state)
    if (tabName === "config") {
      ConfigGenerator.render();
    }
  }

  // --- Toast ---------------------------------------------------------------

  function showToast(msg) {
    var t = $("#toast");
    t.textContent = msg;
    t.classList.add("show");
    setTimeout(function () { t.classList.remove("show"); }, 2000);
  }

  // --- Copy & Download -----------------------------------------------------

  function copyToClipboard() {
    var fmt = ConfigGenerator.getFormat();
    var code = fmt === "configjson" ? ConfigGenerator.getRawConfigJSON() : ConfigGenerator.getRawCode();
    var btn = $("#btn-copy");

    function onSuccess() {
      btn.classList.add("copied");
      btn.textContent = "\u2713 Copied!";
      showToast("Code copied to clipboard!");
      setTimeout(function () {
        btn.classList.remove("copied");
        btn.textContent = "Copy to Clipboard";
      }, 2000);
    }

    if (navigator.clipboard && navigator.clipboard.writeText) {
      navigator.clipboard.writeText(code).then(onSuccess).catch(fallbackCopy);
    } else {
      fallbackCopy();
    }

    function fallbackCopy() {
      var ta = document.createElement("textarea");
      ta.value = code;
      ta.style.position = "fixed";
      ta.style.left = "-9999px";
      document.body.appendChild(ta);
      ta.select();
      try {
        document.execCommand("copy");
        onSuccess();
      } catch (e) {
        showToast("Copy failed \u2014 select the code manually");
      }
      document.body.removeChild(ta);
    }
  }

  function downloadCode() {
    var fmt = ConfigGenerator.getFormat();
    var code, filename;
    if (fmt === "configjson") {
      code = ConfigGenerator.getRawConfigJSON();
      filename = "config.json";
    } else {
      code = ConfigGenerator.getRawCode();
      filename = "code.py";
    }
    var blob = new Blob([code], { type: "text/plain" });
    var url = URL.createObjectURL(blob);
    var a = document.createElement("a");
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    showToast("Downloading " + filename + "\u2026");
  }

  function downloadSerialTest() {
    // Generate the serial test script content
    var code = _generateSerialTestCode();
    var blob = new Blob([code], { type: "text/plain" });
    var url = URL.createObjectURL(blob);
    var a = document.createElement("a");
    a.href = url;
    a.download = "code.py";
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    showToast("Downloading serial test code.py\u2026");
  }

  function _generateSerialTestCode() {
    var s = AppState.getState();
    var btnPins = [];
    var touchPins = [];
    for (var i = 0; i < s.keyAssignments.length; i++) {
      var ka = s.keyAssignments[i];
      if (ka.type === "button") btnPins.push(ka.pin);
      else if (ka.type === "touch") touchPins.push(ka.pin);
    }
    var adcPins = {};
    for (var param in s.fxAssignments) {
      var fa = s.fxAssignments[param];
      if ((fa.source === "pot" || fa.source === "ldr") && fa.pin !== null) {
        adcPins[fa.pin] = true;
      }
    }
    var adcList = [];
    for (var p in adcPins) adcList.push(parseInt(p));

    var hasAccel = false, hasTof = false;
    for (var p2 in s.fxAssignments) {
      var src = s.fxAssignments[p2].source;
      if (src === "accel_x" || src === "accel_y" || src === "accel_shake") hasAccel = true;
      if (src === "tof") hasTof = true;
    }

    var lines = [];
    lines.push("# Serial Test Script -- reports input events over USB serial");
    lines.push("# Flash this to your Pico 2 to test wiring with the web interface.");
    lines.push("# Generated by Config Tool");
    lines.push("");
    lines.push("import board, time, digitalio, analogio, usb_cdc");
    lines.push("");
    lines.push("try:");
    lines.push("    import touchio");
    lines.push("except ImportError:");
    lines.push("    touchio = None");
    lines.push("");
    lines.push("try:");
    lines.push("    import neopixel");
    lines.push("except ImportError:");
    lines.push("    neopixel = None");
    lines.push("");
    lines.push("serial = usb_cdc.console");
    lines.push("");
    lines.push("# LED setup");
    lines.push("led = None");
    lines.push("try:");
    lines.push("    if neopixel:");
    lines.push("        led = neopixel.NeoPixel(board.GP" + s.neopixelPin + ", 1, brightness=0.3)");
    lines.push("        led.fill((20, 0, 40))  # dim purple = idle");
    lines.push("except Exception:");
    lines.push("    pass");
    lines.push("");
    lines.push("connected = False");
    lines.push("led_tick = 0");
    lines.push("");

    // Buttons
    if (btnPins.length > 0) {
      lines.push("# Buttons (pull-up, active LOW)");
      lines.push("buttons = []");
      lines.push("btn_state = []");
      for (var b = 0; b < btnPins.length; b++) {
        lines.push("_b = digitalio.DigitalInOut(board.GP" + btnPins[b] + ")");
        lines.push("_b.direction = digitalio.Direction.INPUT");
        lines.push("_b.pull = digitalio.Pull.UP");
        lines.push("buttons.append(_b)");
        lines.push("btn_state.append(True)  # not pressed");
      }
      lines.push("");
    }

    // Touch
    if (touchPins.length > 0) {
      lines.push("# Touch pads");
      lines.push("touches = []");
      lines.push("touch_state = []");
      lines.push("if touchio:");
      for (var t = 0; t < touchPins.length; t++) {
        lines.push("    try:");
        lines.push("        _t = touchio.TouchIn(board.GP" + touchPins[t] + ")");
        lines.push("        touches.append(_t)");
        lines.push("        touch_state.append(False)");
        lines.push("    except Exception:");
        lines.push("        pass");
      }
      lines.push("");
    }

    // ADC
    if (adcList.length > 0) {
      lines.push("# Analog inputs");
      lines.push("analogs = []");
      for (var a = 0; a < adcList.length; a++) {
        lines.push("try:");
        lines.push("    analogs.append((analogio.AnalogIn(board.GP" + adcList[a] + "), " + adcList[a] + "))");
        lines.push("except Exception:");
        lines.push("    pass");
      }
      lines.push("analog_last = [0.0] * len(analogs)");
      lines.push("");
    }

    // I2C sensors
    if (hasAccel || hasTof) {
      lines.push("# I2C sensors");
      lines.push("i2c = None");
      lines.push("accel = None");
      lines.push("tof = None");
      lines.push("try:");
      lines.push("    import busio");
      lines.push("    i2c = busio.I2C(board.GP" + s.i2cScl + ", board.GP" + s.i2cSda + ")");
      lines.push("except Exception:");
      lines.push("    pass");
      if (hasAccel) {
        lines.push("if i2c:");
        lines.push("    try:");
        lines.push("        import adafruit_lis3dh");
        lines.push("        accel = adafruit_lis3dh.LIS3DH_I2C(i2c)");
        lines.push("    except Exception:");
        lines.push("        pass");
      }
      if (hasTof) {
        lines.push("if i2c:");
        lines.push("    try:");
        lines.push("        import adafruit_vl53l0x");
        lines.push("        tof = adafruit_vl53l0x.VL53L0X(i2c)");
        lines.push("    except Exception:");
        lines.push("        pass");
      }
      lines.push("");
    }

    // Connected LED animation
    lines.push("def led_connected_anim():");
    lines.push("    \"\"\"Rainbow chase to indicate web connection.\"\"\"");
    lines.push("    if not led:");
    lines.push("        return");
    lines.push("    import math");
    lines.push("    for i in range(30):");
    lines.push("        hue = (i * 12) % 360");
    lines.push("        r = int(max(0, min(255, abs(hue / 60 - 3) * 255 - 255)))");
    lines.push("        g = int(max(0, min(255, -(abs(hue / 60 - 2) * 255 - 255))))");
    lines.push("        b = int(max(0, min(255, -(abs(hue / 60 - 4) * 255 - 255))))");
    lines.push("        led.fill((r, g, b))");
    lines.push("        time.sleep(0.04)");
    lines.push("    led.fill((0, 60, 20))  # green = connected");
    lines.push("");
    lines.push("def led_idle_pulse(tick):");
    lines.push("    \"\"\"Slow purple pulse when not connected.\"\"\"");
    lines.push("    if not led:");
    lines.push("        return");
    lines.push("    import math");
    lines.push("    brightness = int(10 + 30 * (0.5 + 0.5 * math.sin(tick * 0.05)))");
    lines.push("    led.fill((brightness, 0, brightness))");
    lines.push("");

    // Main loop
    lines.push("def send(msg):");
    lines.push("    print(msg)");
    lines.push("");
    lines.push("print('READY')");
    lines.push("");
    lines.push("while True:");
    lines.push("    # Check for commands from browser");
    lines.push("    if serial.in_waiting > 0:");
    lines.push("        try:");
    lines.push("            cmd = serial.readline().decode().strip()");
    lines.push("            if cmd == 'CMD:CONNECTED':");
    lines.push("                connected = True");
    lines.push("                led_connected_anim()");
    lines.push("            elif cmd == 'CMD:DISCONNECTED':");
    lines.push("                connected = False");
    lines.push("        except Exception:");
    lines.push("            pass");
    lines.push("");

    if (btnPins.length > 0) {
      lines.push("    # Buttons");
      lines.push("    for i, btn in enumerate(buttons):");
      lines.push("        val = btn.value");
      lines.push("        if val != btn_state[i]:");
      lines.push("            btn_state[i] = val");
      lines.push("            send('B' + str(i) + ':' + ('0' if val else '1'))");
      lines.push("");
    }

    if (touchPins.length > 0) {
      lines.push("    # Touch pads");
      lines.push("    if touchio:");
      lines.push("        for i, tp in enumerate(touches):");
      lines.push("            try:");
      lines.push("                val = tp.value");
      lines.push("                if val != touch_state[i]:");
      lines.push("                    touch_state[i] = val");
      lines.push("                    send('T' + str(i) + ':' + ('1' if val else '0'))");
      lines.push("            except Exception:");
      lines.push("                pass");
      lines.push("");
    }

    if (adcList.length > 0) {
      lines.push("    # Analog");
      lines.push("    for i, (adc, pin) in enumerate(analogs):");
      lines.push("        try:");
      lines.push("            raw = adc.value / 65535");
      lines.push("            if abs(raw - analog_last[i]) > 0.01:");
      lines.push("                analog_last[i] = raw");
      lines.push("                send('A' + str(pin) + ':' + str(round(raw, 3)))");
      lines.push("        except Exception:");
      lines.push("            pass");
      lines.push("");
    }

    if (hasAccel) {
      lines.push("    # Accelerometer");
      lines.push("    if accel:");
      lines.push("        try:");
      lines.push("            x, y, z = accel.acceleration");
      lines.push("            tx = max(-1, min(1, x / 9.8))");
      lines.push("            ty = max(-1, min(1, y / 9.8))");
      lines.push("            mag = (x*x + y*y + z*z) ** 0.5");
      lines.push("            shake = max(0, min(1, (mag - 9.8) / 20))");
      lines.push("            send('TX:' + str(round(tx, 2)))");
      lines.push("            send('TY:' + str(round(ty, 2)))");
      lines.push("            if shake > 0.05:");
      lines.push("                send('SH:' + str(round(shake, 2)))");
      lines.push("        except Exception:");
      lines.push("            pass");
      lines.push("");
    }

    if (hasTof) {
      lines.push("    # ToF");
      lines.push("    if tof:");
      lines.push("        try:");
      lines.push("            dist = tof.range");
      lines.push("            norm = max(0, min(1, dist / 2000))");
      lines.push("            send('TOF:' + str(round(norm, 3)))");
      lines.push("        except Exception:");
      lines.push("            pass");
      lines.push("");
    }

    lines.push("    # LED idle animation");
    lines.push("    if not connected:");
    lines.push("        led_tick += 1");
    lines.push("        if led_tick % 5 == 0:");
    lines.push("            led_idle_pulse(led_tick)");
    lines.push("");
    lines.push("    time.sleep(0.01)");
    lines.push("");

    return lines.join("\n");
  }

  // --- Init ----------------------------------------------------------------

  function init() {
    // Tab buttons
    var tabs = document.querySelectorAll(".tab");
    for (var i = 0; i < tabs.length; i++) {
      tabs[i].addEventListener("click", function () {
        switchTab(this.getAttribute("data-tab"));
      });
    }

    // Copy/download
    var copyBtn = $("#btn-copy");
    if (copyBtn) copyBtn.addEventListener("click", copyToClipboard);
    var dlBtn = $("#btn-download");
    if (dlBtn) dlBtn.addEventListener("click", downloadCode);

    // Format toggle
    var fmtCodePy = $("#btn-fmt-codepy");
    var fmtConfig = $("#btn-fmt-configjson");
    if (fmtCodePy) fmtCodePy.addEventListener("click", function () { ConfigGenerator.setFormat("codepy"); });
    if (fmtConfig) fmtConfig.addEventListener("click", function () { ConfigGenerator.setFormat("configjson"); });

    // Update Pico button
    var updateBtn = $("#btn-update-pico");
    if (updateBtn) {
      updateBtn.addEventListener("click", function () {
        if (!SerialBridge.isConnected()) {
          showToast("Connect your Pico first (click Connect Pico in the header)");
          return;
        }
        updateBtn.disabled = true;
        updateBtn.classList.add("sending");
        updateBtn.textContent = "Sending...";

        SerialBridge.pushConfigAndSave(function (sent, total) {
          updateBtn.textContent = "Sending " + sent + "/" + total + "...";
        }).then(function () {
          updateBtn.classList.remove("sending");
          updateBtn.textContent = "Update Pico";
          updateBtn.disabled = false;
          showToast("Config saved to Pico!");
        }).catch(function (err) {
          updateBtn.classList.remove("sending");
          updateBtn.textContent = "Update Pico";
          updateBtn.disabled = false;
          showToast("Update failed: " + err.message);
        });
      });

      // Enable/disable based on serial connection
      AppState.on("change:serialConnected", function (connected) {
        updateBtn.disabled = !connected;
      });
    }

    // Serial test download link
    var serialLink = $("#link-serial-test");
    if (serialLink) {
      serialLink.addEventListener("click", function (e) {
        e.preventDefault();
        downloadSerialTest();
      });
    }

    // Init synth UI (play tab is active by default)
    SynthUI.init();
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", init);
  } else {
    init();
  }
})();
